#pragma once
#include <QApplication>
#include <QWidget>
#include <QPushButton>
#include <QVBoxLayout>
#include <QAbstractNativeEventFilter>
#include <windows.h>
#include <commctrl.h>
#include <iostream>
#include <chrono>
#include <future>
#include <thread>
#include <mutex>